### ISSUE TITLE
ERRORS LIKE CRAZY XDD

### ISSUE THREAD

**Issue by Bam810bam321** [2ezlma0/cumhook#1]
![image](https://user-images.githubusercontent.com/67829250/214633687-e677d427-0905-454f-85cd-4f56f62b045a.png)

**Comment by seroah** [comment]
full retard

**Comment by 2ezlma0** [comment]
CONFIG ISSUE THREAD CLOSED

**Comment by Cossegosse** [comment]
Hello team I would like to say that this issue has been fixed any no errors will every pop up again 👍
